[package]
name = "spiritos-aarch64"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "spiritos-aarch64"
path = "src/main.rs"

[dependencies]
spiritos-hal    = { path = "../spiritos-hal" }
spiritos-kernel = { path = "../spiritos-kernel" }

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"
